### ISSUE TITLE
Add support for td-agent

### ISSUE THREAD

**Issue by dferreiralopessc** [loggly/fluent-plugin-macos-log#5]
# The problem

This plugin only works with fluentd (and not td-agent).
I tried installing it on my macOS (10.15) but I can't make it work.

Here is the error I get when installing it
```bash
sudo gem install fluentd --no-doc
Building native extensions. This could take a while...
ERROR:  Error installing fluentd:
	ERROR: Failed to build gem native extension.
    current directory: /Library/Ruby/Gems/2.6.0/gems/msgpack-1.4.2/ext/msgpack
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby -I /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0 -r ./siteconf20210422-50294-1lths6v.rb extconf.rb
checking for ruby/st.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.
Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/$(RUBY_BASE_NAME)
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:467:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
```

I found multiple posts related to this error and the solutions provided did not work for me. Here are a few ones I tried:
* https://stackoverflow.com/questions/27768420/gem-installation-error-you-have-to-install-development-tools-first
* https://stackoverflow.com/questions/20939568/error-error-installing-cocoapods-error-failed-to-build-gem-native-extension
* https://github.com/CocoaPods/CocoaPods/issues/1727

It is clear that I lack tools for building fluentd. I looked at the requirements on fluentd and the one I am not 100% sure I have is the `ruby-dev` one (see Step 1 [here](https://docs.fluentd.org/installation/install-by-gem)).
I tried different things here as well like installing `ruby-build` using homebrew but it did not work.

Unless I am missing something trivial, I believe this installation path for macOS is very hard to achieve at huge scale.
I expect others will run into the same issues and for this reason I recommend the below solution.

# A solution

A good way for simplifying the deployment would be to make this plugin compatible with td-agent.
Td-agent installation is really straightforward.

This plugin has conflicts on gemfiles with the ones from td-agent.
I was able to remove those conflicts but the agent as soon as it runs the input configure function (on the call to `super`).
I did not find a solution yet but I wanted to open an issue in the meantime to see with the owners if all the above makes sense.

Here is what I currently have for the gemspec file
```
  spec.required_ruby_version     = ">= 2.3.0"
  spec.required_rubygems_version = ">= 2.6.7"

  #spec.add_dependency "fluentd", '>= 1.2', '< 2'
  spec.add_dependency "yajl-ruby", '~> 1.3'

  spec.add_development_dependency "bundler", "~> 2.0"
  spec.add_development_dependency "rake", "~> 13.0"
  spec.add_development_dependency "minitest", "~> 5.0"
  spec.add_development_dependency "test-unit", "~> 3.2"
```

I am doing the tests using version 0.0.2

# Thank you

This plugin looks amazing. I am really happy to see I am not the only one struggling with macOS logs.
There is a lot of value on Unified Apple Logs and I am surprised there is no easy solution to centralize them. Many thanks for your work

**Comment by langrp** [comment]
Hi, thanks for reaching. I think you’ve got a valid point. The fluentd may not be so straightforward to install and we should make plug-in compatible with td-agent.

Could you provide us version of td-agent you tried?

**Comment by dferreiralopessc** [comment]
Hi @langrp, 

I am currently working with the fluentd team to have a new version of `td-agent` released on macOS.
The build successfully went trough and the tests I did locally with this plugin works.

If the new release is available for download, I believe we can close the issue.

Here is the link to the latest macOS release in case you want to test it: https://github.com/fluent-plugins-nursery/td-agent-builder/actions/runs/787556103

**Comment by langrp** [comment]
Hi @dferreiralopessc,

It sounds good, I've added support for `td-agent` v3 so it won't require update for those running on `td-agent` already. You can test this with [fluent-plugin-macos-log-0.0.3.beta.1.gem.zip](https://github.com/loggly/fluent-plugin-macos-log/files/6406072/fluent-plugin-macos-log-0.0.3.beta.1.gem.zip)

**Comment by dferreiralopessc** [comment]
@langrp this is amazing, I'll test it and get back to you if I find any issues.

Many thanks for your work!
