### ISSUE TITLE
Unknown input plugin 'macoslog'

### ISSUE THREAD

**Issue by ameyah** [loggly/fluent-plugin-macos-log#7]
Hello,

New to fluentd, and trying to fetch macos unified logs.

I installed `fluent-plugin-macos-log` with td-agent-gem:

```
% sudo /opt/td-agent/embedded/bin/fluent-gem list --local | grep macos-log
fluent-plugin-macos-log (0.0.3)
```

But when I start td-agent, I get the following error in the logs:

```
2021-08-16 17:29:27 -0700 [info]: parsing config file is succeeded path="/etc/td-agent/td-agent.conf"
2021-08-16 17:29:27 -0700 [error]: config error file="/etc/td-agent/td-agent.conf" error_class=Fluent::ConfigError error="Unknown input plugin 'macoslog'. Run 'gem search -rd fluent-plugin' to find plugins"
```

Am I missing something?

**Comment by langrp** [comment]
Hi,
So sorry on delay on this. For some reason Github does not notify me.

This does look like the plugin was not installed properly:
1. Was there any error during installation?
2. Could you verify content of the installation folder `/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-macos-log-0.0.3`?
3. Verify the td-agent started using the embedded ruby installation?

**Comment by ameyah** [comment]
Hello, Thanks for the response!

1. No error during installation
2. The contents are empty :( 
3. Yes

(2) seems an issue. I tried reinstalling, but still empty with no error during installation.

**Comment by langrp** [comment]
Could you provide more detailed installation log using verbose or debug option?

```
/opt/td-agent/embedded/bin/fluent-gem install -V fluent-plugin-macos-log
```

**Comment by ameyah** [comment]
Apologies for not getting back earlier. This seems some issue with fluent setup. The gem is working on a different device.

Thanks for your responses!
